### ISSUE TITLE
Extract Class Property Goes Wrong

### ISSUE THREAD

**Issue by chan15** [adoy/vim-php-refactoring-toolbox#11]
```php
<?php

class Test
{
    public function getName($name = null)
    {
        $myName = $name;
    }
}
```

If I <Leader>ep on `$myName`, it turns to

```php
<?php

class Test
{
    /**
     * @var mixed
     */
    private $$myName;

    public function getName($name = null)
    {
        $myName = $name;
    }
}
```

According to the document, it should be:

```php
<?php

class Test
{
    /**
     * @var mixed
     */
    private $myName;

    public function getName($name = null)
    {
        $this->myName = $name;
    }
}
```

VIM: 7.4

**Comment by adoy** [comment]
Could you please confirm this fix the issue ? Thanks :-)

**Comment by chan15** [comment]
the plugin is already updated, but still the same

**Comment by chan15** [comment]
I record my procedure for you

https://youtu.be/fgF053QmEns

**Comment by adoy** [comment]
The updated plugin is not yet merged on the master branch. I'm waiting for
the confirmation that the fix is correct to do it.

Could you please checkout the bug-11 branch to test again ?

Thanks

**Comment by chan15** [comment]
It's work perfectly thanks

**Comment by chan15** [comment]
dear @adoy , when will you merge this to master, it's test ok~

**Comment by adoy** [comment]
Done :)
