### ISSUE TITLE
<leader>rlv is case insensitive

### ISSUE THREAD

**Issue by joereynolds** [adoy/vim-php-refactoring-toolbox#20]
Not sure if this is intended but when I try to rename a variable, from `$taskID` to `$taskId` I get the following warning:

`$taskId seems to already exist in the current function scope. Rename anyway?`

When I proceed to rename, nothing changes, the function still has the old name.

Thanks!

**Comment by adoy** [comment]
Hi,

I suspect that you have smartcase enabled could you please do 
`:set nosmartcase`
and try again ?

**Comment by joereynolds** [comment]
Hi,

Doing `set smartcase?` reveals that I don't have smartcase enabled.

To reproduce:

Put this code in a file

```
    public function taskExists($taskID)
    {
        $taskID = (int) $taskID;

        if (0 >= $taskID) {
            return false;
        }

        return  $taskID;
    }
```

Go to any of the `$taskID` variables and hit <leader>rlv
When prompted, type in taskid
It will say that name already exists.

**Comment by adoy** [comment]
Could you please test the fix on the bug-20 branch ?

**Comment by joereynolds** [comment]
That seems to fix it!
Thanks for the prompt fix :D
