### ISSUE TITLE
This is a nice tool, but is not perfect enough, i got some bug here...

### ISSUE THREAD

**Issue by liangguohuan** [adoy/vim-php-refactoring-toolbox#21]
- nvim --version: 0.1.6-dev
- Vim (version: ):  8.0
- Operating system/version: Ubuntu 14.04.5 LTS
- Terminal name/version: Gnome-Terminal: 3.6.2
  
  ```
                  ////////// disable gitgutter //////////
  ```

Error detected while processing function PhpExtractMethod:
line   41:
E20: Mark not set
2 lines to indent...
3 lines indented
2 lines to indent...
3 lines indented
line   53:
E20: Mark not set
5 fewer lines; before #463  11 seconds ago
Error detected while processing function PhpExtractMethod:
line   41:
E20: Mark not set
2 lines to indent...
3 lines indented
2 lines to indent...
3 lines indented
line   53:
E20: Mark not set
Error detected while processing function PhpRenameMethod[3]..<SNR>163_PhpSearchInCurrentClass:
line    7:
E20: Mark not set
Error detected while processing function PhpRenameMethod[11]..<SNR>163_PhpReplaceInCurrentClass:
line    8:
E20: Mark not set
Error detected while processing function PhpRenameMethod[3]..<SNR>163_PhpSearchInCurrentClass:
line    7:
E20: Mark not set
Error detected while processing function PhpRenameMethod[11]..<SNR>163_PhpReplaceInCurrentClass:
line    8:
E20: Mark not set

```
                        ////////// enable gitgutter //////////
```

Error detected while processing function gitgutter#undo_hunk[6]..gitgutter#diff#run_diff:
line   83:
E605: Exception not caught: diff failed
Error detected while processing function gitgutter#undo_hunk:
line    6:
E171: Missing :endif
Error detected while processing function PhpRenameMethod[3]..<SNR>169_PhpSearchInCurrentClass[1]..gitgutter#undo_hunk[6]..gitgut
ter#diff#run_diff:
line   83:
E605: Exception not caught: diff failed
Error detected while processing function PhpRenameMethod[3]..<SNR>169_PhpSearchInCurrentClass[1]..gitgutter#undo_hunk:
line    6:
E171: Missing :endif
Error detected while processing function PhpRenameMethod:
line    3:
E171: Missing :endif
Error detected while processing function PhpRenameMethod[3]..<SNR>169_PhpSearchInCurrentClass[1]..gitgutter#undo_hunk[6]..gitgut
ter#diff#run_diff:
line   83:
E605: Exception not caught: diff failed
Error detected while processing function PhpRenameMethod[3]..<SNR>169_PhpSearchInCurrentClass[1]..gitgutter#undo_hunk:
line    6:
E171: Missing :endif
Error detected while processing function PhpRenameMethod:
line    3:
E171: Missing :endif

**Comment by dylanhsieh** [comment]
E20: Mark not set
I think you have a hot key mapping to 'm',
it use set mark,  and got mark to replace the content,
in 
you can see the code in vim-php-refactoring-toolbox/plugin/php-refactoring-toolbox.vim

223    normal mr
           ....
238    normal `r

mr	set mark a at current cursor location
'r	jump to line of mark a (first non-blank character in line)
I fix this problem by disable my  'm' hot key.
maybe it will help you.

**Comment by adoy** [comment]
This should be fixed in the master branch. Thanks to reopen if you still have issues
