### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mlopezgva** [adoy/vim-php-refactoring-toolbox#3]
Hello.. Any documentation in ear future? Just to check it out without having to come to github or vim.org...

Thanks.

**Comment by jrean** [comment]
Fantastic plugin!
Same question.
How can I set the indentation because each time the plugin inserts something I need to fix the indentation.

I use the following within my vimrc

```
set tabstop=3          " width of a tab character
set softtabstop=3    " white space(s) to be inserted
set shiftwidth=3       " white space(s) to be removed
```

Thank you.

**Comment by adoy** [comment]
Hi,

@mlopezgva Unfortunately I have no time to write the documentation those days but feel free to contribute and add it to this project :)

@jrean Hi, i'll have a look in a near future to this and to your pull request. I'll get back to you ASAP.

Thanks

**Comment by jrean** [comment]
Hi @adoy, no problem. I wait for you to come back.
If you are agree I would to love to help you improve the plugin with suggestions :)
Let's keep in touch.
Thank you for your work!
I will submit some few others issues.

**Comment by vivoconunxino** [comment]
Hey, I eventually decided to add some doc to this really nice pluggin. This is the first time I do something like that (even the first time I contribute at github), also English isn't my main language but I reused most of your Readme so I don't expect many grammar errors. Well.. I hope you find it useful.

**Comment by vivoconunxino** [comment]
Oh, I forgot to tell you that I've abbreviated vim-php-refactoring-toolbox into refactoring-toolbox into the doc, so It's easier to find it through :help command. Feel free to change it as you like if you finally accept the pull request.

**Comment by adoy** [comment]
Pull request was accepted but this issue was never closed. Thanks again for your help on this.
