### ISSUE TITLE
Custom Visibility

### ISSUE THREAD

**Issue by jrean** [adoy/vim-php-refactoring-toolbox#7]
Hi,

Great plugin!
- It would be great to allow one to set a custom visibility (private|protected|public|static|abstract) when adding and/or extracting a variable.
- It would be great to allow one to set a custom visibility (private|protected|public|static|abstract) when extracting a selection to create a new method.

What do you think?

I sent you two pull requests for each case. I kept your default behaviour setting the variable and/or method as private.

https://github.com/adoy/vim-php-refactoring-toolbox/pull/8
https://github.com/adoy/vim-php-refactoring-toolbox/pull/9

:-)

**Comment by adoy** [comment]
Thanks for your contributions. I merged them and added few things.
